management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
endpoints:
  shutdown:
    enabled: 'true'
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true '
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: 'true '
        id:
          new_generator_mappings: 'true'
        show_sql: 'false '
        type: trace
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    username: root
    tomcat:
      max-idle: '20'
      max-active: '50'
      max-wait: '20000'
      min-idle: '15'
    url: jdbc:mysql://localhost:3306/laboutique?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin&useSSL=false
logging:
  level:
    org:
      hibernate:
        nodeValue: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE '
        SQL: DEBUG
      springframework:
        web: WARN
    com:
      accademia: DEBUG
    root: WARN
multipart:
  maxFileSize: 2048KB
  maxRequestSize: 2048KB
